/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppMonitoringRouteImport } from './routes/_app/monitoring'
import { Route as AppLiveMapRouteImport } from './routes/_app/live-map'
import { Route as AppHotspotsRouteImport } from './routes/_app/hotspots'
import { Route as AppForecastRouteImport } from './routes/_app/forecast'
import { Route as AppExplanationsRouteImport } from './routes/_app/explanations'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as ApiAlertsBulkAckRouteImport } from './routes/api/alerts/bulk-ack'
import { Route as ApiSegmentsIdUpstreamRouteImport } from './routes/api/segments/$id/upstream'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveMapRoute = AppLiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => AppRoute,
} as any)
const AppHotspotsRoute = AppHotspotsRouteImport.update({
  id: '/hotspots',
  path: '/hotspots',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppExplanationsRoute = AppExplanationsRouteImport.update({
  id: '/explanations',
  path: '/explanations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const ApiAlertsBulkAckRoute = ApiAlertsBulkAckRouteImport.update({
  id: '/api/alerts/bulk-ack',
  path: '/api/alerts/bulk-ack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSegmentsIdUpstreamRoute = ApiSegmentsIdUpstreamRouteImport.update({
  id: '/api/segments/$id/upstream',
  path: '/api/segments/$id/upstream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/explanations': typeof AppExplanationsRoute
  '/forecast': typeof AppForecastRoute
  '/hotspots': typeof AppHotspotsRoute
  '/live-map': typeof AppLiveMapRoute
  '/monitoring': typeof AppMonitoringRoute
  '/settings': typeof AppSettingsRoute
  '/api/alerts/bulk-ack': typeof ApiAlertsBulkAckRoute
  '/api/segments/$id/upstream': typeof ApiSegmentsIdUpstreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AppAlertsRoute
  '/dashboard': typeof AppDashboardRoute
  '/explanations': typeof AppExplanationsRoute
  '/forecast': typeof AppForecastRoute
  '/hotspots': typeof AppHotspotsRoute
  '/live-map': typeof AppLiveMapRoute
  '/monitoring': typeof AppMonitoringRoute
  '/settings': typeof AppSettingsRoute
  '/api/alerts/bulk-ack': typeof ApiAlertsBulkAckRoute
  '/api/segments/$id/upstream': typeof ApiSegmentsIdUpstreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/explanations': typeof AppExplanationsRoute
  '/_app/forecast': typeof AppForecastRoute
  '/_app/hotspots': typeof AppHotspotsRoute
  '/_app/live-map': typeof AppLiveMapRoute
  '/_app/monitoring': typeof AppMonitoringRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/alerts/bulk-ack': typeof ApiAlertsBulkAckRoute
  '/api/segments/$id/upstream': typeof ApiSegmentsIdUpstreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/explanations'
    | '/forecast'
    | '/hotspots'
    | '/live-map'
    | '/monitoring'
    | '/settings'
    | '/api/alerts/bulk-ack'
    | '/api/segments/$id/upstream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/explanations'
    | '/forecast'
    | '/hotspots'
    | '/live-map'
    | '/monitoring'
    | '/settings'
    | '/api/alerts/bulk-ack'
    | '/api/segments/$id/upstream'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/alerts'
    | '/_app/dashboard'
    | '/_app/explanations'
    | '/_app/forecast'
    | '/_app/hotspots'
    | '/_app/live-map'
    | '/_app/monitoring'
    | '/_app/settings'
    | '/api/alerts/bulk-ack'
    | '/api/segments/$id/upstream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiAlertsBulkAckRoute: typeof ApiAlertsBulkAckRoute
  ApiSegmentsIdUpstreamRoute: typeof ApiSegmentsIdUpstreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitoring': {
      id: '/_app/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live-map': {
      id: '/_app/live-map'
      path: '/live-map'
      fullPath: '/live-map'
      preLoaderRoute: typeof AppLiveMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hotspots': {
      id: '/_app/hotspots'
      path: '/hotspots'
      fullPath: '/hotspots'
      preLoaderRoute: typeof AppHotspotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forecast': {
      id: '/_app/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explanations': {
      id: '/_app/explanations'
      path: '/explanations'
      fullPath: '/explanations'
      preLoaderRoute: typeof AppExplanationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/alerts/bulk-ack': {
      id: '/api/alerts/bulk-ack'
      path: '/api/alerts/bulk-ack'
      fullPath: '/api/alerts/bulk-ack'
      preLoaderRoute: typeof ApiAlertsBulkAckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/segments/$id/upstream': {
      id: '/api/segments/$id/upstream'
      path: '/api/segments/$id/upstream'
      fullPath: '/api/segments/$id/upstream'
      preLoaderRoute: typeof ApiSegmentsIdUpstreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExplanationsRoute: typeof AppExplanationsRoute
  AppForecastRoute: typeof AppForecastRoute
  AppHotspotsRoute: typeof AppHotspotsRoute
  AppLiveMapRoute: typeof AppLiveMapRoute
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExplanationsRoute: AppExplanationsRoute,
  AppForecastRoute: AppForecastRoute,
  AppHotspotsRoute: AppHotspotsRoute,
  AppLiveMapRoute: AppLiveMapRoute,
  AppMonitoringRoute: AppMonitoringRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiAlertsBulkAckRoute: ApiAlertsBulkAckRoute,
  ApiSegmentsIdUpstreamRoute: ApiSegmentsIdUpstreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
